version: '3.8'

services:
  postgres: # 使用 postgres:14 這個官方的 image
    image: postgres:14 
    container_name: postgres 
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: accountint_app_seperating_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    container_name: backend
    environment:
      DATABASE_URL: "postgresql://your_user:your_password@postgres:5432/your_database"
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app  # 將本機程式碼掛載進容器
      - ./backend/requirements.txt:/app/requirements.txt
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - postgres
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    volumes: # 這行是為了讓容器內的程式碼可以透過 volume 即時更新 (hot-reloading)
      - ./frontend:/app/frontend/
    ports:
      - 3000:3000
    depends_on:
      - backend

  
  pgadmin: 
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
